from __future__ import annotations

from enum import Enum


class StrEnum(str, Enum):
    def __str__(self) -> str:
        return self.value


class NodeStatus(StrEnum):
    PENDING = "PENDING"
    READY = "READY"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"
    CANCELLED = "CANCELLED"


class TaskTerminalState(StrEnum):
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    NEEDS_HUMAN = "NEEDS_HUMAN"
    UNSAFE = "UNSAFE"
    TIMEOUT = "TIMEOUT"
    BUDGET_EXCEEDED = "BUDGET_EXCEEDED"
    NO_PROGRESS = "NO_PROGRESS"
    CANCELLED = "CANCELLED"


class CapabilityKind(StrEnum):
    OBSERVATION = "observation"
    COMPUTE = "compute"
    ACTION = "action"
    PROCEDURE = "procedure"
    TASK = "task"
    RECOVERY = "recovery"


class RiskClass(StrEnum):
    NONE = "NONE"
    READ_ONLY_HARDWARE = "READ_ONLY_HARDWARE"
    MOTION = "MOTION"
    GRIPPER = "GRIPPER"
    CONTACT = "CONTACT"
    RELEASE = "RELEASE"
    RECOVERY = "RECOVERY"
    HIGH_RISK = "HIGH_RISK"


class ErrorCategory(StrEnum):
    INPUT = "INPUT"
    PERCEPTION = "PERCEPTION"
    FRAME = "FRAME"
    PRECONDITION = "PRECONDITION"
    MOTION = "MOTION"
    GRIPPER = "GRIPPER"
    ROBOT_STATE = "ROBOT_STATE"
    VERIFICATION = "VERIFICATION"
    RECOVERY = "RECOVERY"
    AUTHORIZATION = "AUTHORIZATION"
    TIMEOUT = "TIMEOUT"
    RESOURCE = "RESOURCE"
    INTERNAL = "INTERNAL"
    UNKNOWN = "UNKNOWN"


class ErrorCode(StrEnum):
    UNKNOWN_ERROR = "UNKNOWN_ERROR"
    INVALID_INPUT = "INVALID_INPUT"
    SCHEMA_VALIDATION_FAILED = "SCHEMA_VALIDATION_FAILED"
    CAPABILITY_NOT_FOUND = "CAPABILITY_NOT_FOUND"
    CAPABILITY_UNSUPPORTED = "CAPABILITY_UNSUPPORTED"
    CAPABILITY_EXECUTION_FAILED = "CAPABILITY_EXECUTION_FAILED"
    AUTHORIZATION_DENIED = "AUTHORIZATION_DENIED"
    PERCEPTION_NOT_FOUND = "PERCEPTION_NOT_FOUND"
    PERCEPTION_LOW_CONFIDENCE = "PERCEPTION_LOW_CONFIDENCE"
    PERCEPTION_STALE = "PERCEPTION_STALE"
    FRAME_OR_CALIBRATION_INVALID = "FRAME_OR_CALIBRATION_INVALID"
    PRECONDITION_FALSE = "PRECONDITION_FALSE"
    MOTION_IK_INFEASIBLE = "MOTION_IK_INFEASIBLE"
    MOTION_COLLISION_RISK = "MOTION_COLLISION_RISK"
    MOTION_TARGET_NOT_REACHED = "MOTION_TARGET_NOT_REACHED"
    MOTION_TIMEOUT = "MOTION_TIMEOUT"
    CONTACT_FORCE_EXCEEDED = "CONTACT_FORCE_EXCEEDED"
    GRASP_NOT_CONFIRMED = "GRASP_NOT_CONFIRMED"
    OBJECT_DROPPED = "OBJECT_DROPPED"
    RELEASE_NOT_CONFIRMED = "RELEASE_NOT_CONFIRMED"
    ROBOT_WARNING = "ROBOT_WARNING"
    ROBOT_FAULT = "ROBOT_FAULT"
    ROBOT_UNREACHABLE = "ROBOT_UNREACHABLE"
    ROBOT_ESTOP_OR_UNSAFE = "ROBOT_ESTOP_OR_UNSAFE"
    VERIFICATION_FAILED = "VERIFICATION_FAILED"
    RECOVERY_FAILED = "RECOVERY_FAILED"
    RESOURCE_CONFLICT = "RESOURCE_CONFLICT"
    BUDGET_EXCEEDED = "BUDGET_EXCEEDED"
    NO_PROGRESS = "NO_PROGRESS"
    INVALID_STATE_TRANSITION = "INVALID_STATE_TRANSITION"
    EXECUTION_PRECONDITION_FAILED = "EXECUTION_PRECONDITION_FAILED"
    INPUT_BINDING_FAILED = "INPUT_BINDING_FAILED"
    NODE_TIMEOUT = "NODE_TIMEOUT"
    TASK_TIMEOUT = "TASK_TIMEOUT"
    EXECUTION_INTERRUPTED = "EXECUTION_INTERRUPTED"
    CHECKPOINT_CORRUPT = "CHECKPOINT_CORRUPT"
    CHECKPOINT_MISMATCH = "CHECKPOINT_MISMATCH"
    EVENT_LOG_CORRUPT = "EVENT_LOG_CORRUPT"
    RESOURCE_ACQUISITION_FAILED = "RESOURCE_ACQUISITION_FAILED"
    REPLAN_REQUIRED = "REPLAN_REQUIRED"
    HUMAN_ACTION_REQUIRED = "HUMAN_ACTION_REQUIRED"
    NO_TERMINAL_PATH = "NO_TERMINAL_PATH"
    NON_DETERMINISTIC_GRAPH = "NON_DETERMINISTIC_GRAPH"
    PARALLEL_EXECUTION_NOT_SUPPORTED_IN_S7 = "PARALLEL_EXECUTION_NOT_SUPPORTED_IN_S7"


class ErrorSeverity(StrEnum):
    INFO = "INFO"
    WARNING = "WARNING"
    RECOVERABLE = "RECOVERABLE"
    FATAL = "FATAL"
    UNSAFE = "UNSAFE"


class ActionStatus(StrEnum):
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    PLANNED_ONLY = "PLANNED_ONLY"
    DENIED = "DENIED"
    CANCELLED = "CANCELLED"
    TIMEOUT = "TIMEOUT"


class ResourceMode(StrEnum):
    SHARED = "shared"
    EXCLUSIVE = "exclusive"
